
* Homework Questions(Weeks 1 & 2)

** General Probability Questions

 
1) **If there are N students taking COMP3331/9331, what is the probability that note of them 
has a birthday on the first day of the class? (Assume there are exactly 365 days in a year)**

2) How many students would there need to be in the class for the probability in (1) be less
than 50%?

3) What is the probability that five years running, no student has a birthday on the first
day of the class? (Assume the same number of students take the class each year, and no one
repeats the class)

4) Would you answer to (3) above be larger or smaller if one or two more students retook the 
class within the five-year period?


** Networking Questions

*** Q1) What is meant by the term statistical multiplexing

In statistical multiplexing, data from multiple users (senders) is sent over a link.
If one user does not use its share of the bandwith, it is then free to be userd by other users.
Thus, senders share the link bandwith, with no user having all of the link bandwith allocate to it.

*** Q2) Consider two hosts, A and B, connected by a single link of rate R bps. Suppose that the two hosts are separated by m meters, and suppose the propagation speed along the link is s meters/sec. Host A is to send a packet of size L bits to Host B.

(a) Express the propagation delay, d_prop in terms of m and s.

d_prop = m / s

(b) Determine the transmission time of packet, d_trans in terms of L and R 

d_trans = L / R 

(c) Ignoring the processing and queuing delays, obtain an expression for the end-to-end delay.

End-to-end delay is d_prop + d_trans = m/s + L/R 

(d) Suppose Host A begins to transmit the packet at time t=0. At time t = d_trans, where is the last bit of the packet?

The bit is just leaving host A

(e) Suppose Hos
